### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ildella** [MilanoTechScene/milanotechscene.github.io#5]
mancano:
- [x] 1. URL ai meetup e agli eventi
- [x] 2. finire di mappare i dati che servono
- [x] 3. rimuovere la modal con i dettagli di ogni gruppo, per ora non serve
- [x] 4. fixare il calendario esteticamente. 
- [x] 5. mettere il calendar embedded in una pagina su milanotechscene.it

**Comment by stefanobaghino** [comment]
We can close this one as well, right?
